APP_NAME = "genspa"
RTA_OK = 0
RTA_ERROR = 1
CHROMIUM_PATH='C:\\Users\\jibagnato\\PycharmProjects\\kartdetector\\drivers\\chromedriver_win32\\chromedriver.exe'
DISK_CACHE='./build'
IMG_DIR = "C:\\Users\\jibagnato\\PycharmProjects\\genspaclassifier\\genetic-spa-classifier\\screenshots\\"
PATTERN_DIR = "C:\\Users\\jibagnato\\PycharmProjects\\genspaclassifier\\genetic-spa-classifier\\patterns\\"
OUT_DIR = "C:\\Users\\jibagnato\\PycharmProjects\\genspaclassifier\\genetic-spa-classifier\\output\\"
DEBUG_SHOW_PATTERN_IMAGES = False
N_JOBS = 8
SCREEN_RES = 1.0
TESSERACT_TIMEOUT = 1.6
MAX_SCORE_STOP = 8.5
INVALID_GENOMA_RETRIES = 1 # this may impact in longer training times
EARLY_STOP=5  # if after number of epochs doesnt improve, then stops
