APP_NAME = "genspa"
RTA_OK = 0
RTA_ERROR = 1
CHROMIUM_PATH='/Users/jbagnato/chromedriver'
DISK_CACHE='./build'
IMG_DIR = "/Users/jbagnato/github-folders/genetic-spa-classifier/screenshots/"
PATTERN_DIR = "/Users/jbagnato/github-folders/genetic-spa-classifier/patterns/"
OUT_DIR = "/Users/jbagnato/github-folders/genetic-spa-classifier/output/"
DEBUG_SHOW_PATTERN_IMAGES = False
TOP_BEST_TO_ADD = 3
NUM_BEST_TO_ADD = 2
N_JOBS = 4
SCREEN_RES = 2.0
TESSERACT_TIMEOUT = 1.5
MAX_SCORE_STOP = 8.5